classDiagram
    class Protagonist {
        <<abstract>>
        +String Name
        +String SourceSerie
        +Interacting(Protagonist otherProtagonist)
    }

    class ShonenHero {
        +String MainAbility
        +String Slogan
        +Fighting()
        +Interacting(Protagonist otherProtagonist)
        +Empowering(cause: string)
    }
    
    class SeinenHero {
        +String Purpose
        +Float Accomplished
        +Reasoning()
        +Interacting(Protagonist otherProtagonist)
    }
    
    class Season {
        +Int Number
        +List<Episode> Episode
    }
    
    class Episode {
        +String Title
        +Int DurationInMinutes
    }
    
    class Serie {
        +String Title
        +Int BeginningYear
        +String Genre
        +List<Season> Season
        +CalculatingTotaleDuration()
    }

    class IBecomeStronger {
        <<interface>>
        +Empowering(cause: string)
    }

    %% Relations
    Protagonist <|-- ShonenHero : inherits
    Protagonist <|-- SeinenHero : inherits
    ShonenHero ..|> IBecomeStronger : implements
    Serie "1" -- "0..*" Season : contains
    Season "1" -- "0..*" Episode : contains
    Protagonist "0..*" -- "1" Serie : appearsIn

